/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: '#0a0a12',
        surface: '#0f0f1a',
        'surface-container': '#141422',
        'surface-container-low': '#111118',
        'surface-container-high': '#1e1e30',
        'surface-container-highest': '#28283e',
        'surface-variant': '#1e1e30',
        'surface-dim': '#0f0f1a',
        'surface-bright': '#1a1a2e',
        primary: '#ff2d78',
        'primary-container': '#b3004e',
        secondary: '#00ffcc',
        'secondary-container': '#004d3d',
        tertiary: '#ffe04a',
        'tertiary-container': '#665200',
        'on-surface': '#e8e0f0',
        'on-surface-variant': '#a098b0',
        'on-background': '#e8e0f0',
        'on-primary': '#1a0010',
        'on-secondary': '#001a1a',
        'on-tertiary': '#1a1000',
        'on-primary-container': '#ffe0ec',
        'on-secondary-container': '#c0fff4',
        'on-tertiary-container': '#fff0c0',
        outline: '#5a5068',
        'outline-variant': '#302840',
        error: '#ff4444',
        'error-container': '#3d0f0f',
        'on-error': '#1a0000',
        'on-error-container': '#ffa0a0',
        'inverse-surface': '#e8e0f0',
        'inverse-on-surface': '#0a0a12',
        'inverse-primary': '#8c0038',
      },
      fontFamily: {
        headline: ['Sora', 'sans-serif'],
        display: ['Sora', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Space Grotesk', 'monospace'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
}
